function [fps,frames,flag] = ImportVidMat(vid_name,appendtomatfile)
%[fps,frames] = ImportVidMat(vid_name,appendtomatfile,crop)
%  Imports video from the specified file
%  VID_NAME:  file to read
%  flag: any flag that video loading/saving code generates

%  Auto-generated by MATLAB on 11-Feb-2016 16:21:40
% and modified by Mahmut Demir
switch nargin
    case 2
    case 1
        appendtomatfile = 0; % donot append and save the obtained frames
    case 0
        help ImportVidMat
        error('provide video name')
end
    


%check the file extension
[~,~,ext] = fileparts(vid_name);
if strcmp(ext,'.avi')
    % Import the file
    vidobj = VideoReader(vid_name); % read video object
    fps = vidobj.FrameRate; % get frame rate
    framest = importdata(vid_name);  % import frames
    framest = rmfield(framest,'colormap'); % remove colormap
    % initiate the matrix
    frames = zeros(size(framest(1).cdata,1),size(framest(1).cdata,2),numel(framest),'uint8');
    % make the matrix
    try
        for i = 1:numel(framest)
            frames(:,:,i) = framest(i).cdata;
        end
    catch
        for i = 1:numel(framest)
            fm = framest(i).cdata;
            frames(:,:,i) = fm(:,:,1);
        end
    end
    clear framest
elseif strcmp(ext,'.mj2')
    try
        vidobj = VideoReader(vid_name);
        fps = vidobj.FrameRate; % get frame rate
        frames = importdata(vid_name);
        frames = squeeze(frames);
    catch
        disp('Will attempt to saves frames in a matfile.')
        disp('If append option (default: not selected is selected check your files for missing data')
        [fps,frames] = SaveVideoFrames(vid_name);
        appendtomatfile = false; % do not append
        flag.mj2 = 1;
        flag.appendtomatfile = 0;
    end
else
    error('did not code for this file type')
end
if appendtomatfile==1
    save([vidobj.path, oss, strcat(vidobj.name(1:end-3),'mat')],'frames','-append');
end
if ~exist('flag','var')
    flag = [];
end
    